### ISSUE TITLE
Add/Edit Review Form Field Alignment and Bugs

### ISSUE THREAD

**Issue by krusta80** [krusta80/git-committed#69]
Fields need to aligned, and the overall look-and-feel of the page can be tweaked a bit for a better look.

**Comment by krusta80** [comment]
Also, description should NOT be required (although I could be wrong), and perhaps we should allow 0 stars?

**Comment by cjkb90** [comment]
I disagree on 0 stars, no review site I know allows you to do this. Description is required in the back end, I don't think I did anything for this on the front end.
